platform :ios, '13.0'

# Henter Flutter-oppsettet automatisk
import '../../flutter/packages/flutter_tools/bin/xcode_backend.rb'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.expand_path(__file__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Forteller iOS-kompilatoren på GitHub at vi trenger GPS-tillatelse
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'PERMISSION_LOCATION=1']
    end
  end
end
