name: Flutter iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Unsigned iOS IPA
        run: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..
          # Endret fra --simulator til å bygge et rent usignert ipa-arkiv
                    flutter build ipa --no-codesign --allow-provisioning-device-registration


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-output
          # Ny bombesikker bane for ukompilerte app-filer beregnet på fysiske enheter:
          path: build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app/




